version: "3"
services:
  ataru-dev-db:
    build: ./test-postgres
    environment:
      - POSTGRES_DB=oppijantunnistusdb
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"